name: ci-test
on:
  workflow_dispatch:
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create-pr
        run: |
          echo "Hello, world!"
          gh pr create \
            --title "リリース用PR" \
            --body "このPRはリリースに向けた変更を含んでいます。" \
            --base main \
            --head feature-branch \
            --label release
