name: ci-test
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create-label
        run: |
          if ! gh label list | grep -q "^release\s"; then
            gh label create release --color FF0000 --description "Release用のラベル"
          fi

      - name: create-pr
        run: |
          echo "Hello, world!"
          gh pr create \
            --title "リリース用PR" \
            --body "このPRはリリースに向けた変更を含んでいます。" \
            --base main \
            --head feature-branch \
            --label release
