name: ci-test
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create-release
        run: |
          gh release create v1.0.0 --title "リリース v1.0.0" --notes "リリース内容の説明"

      - name: create-pr
        run: |
          echo "Hello, world!"
          gh pr create \
            --title "リリース用PR" \
            --body "このPRはリリースに向けた変更を含んでいます。" \
            --base main \
            --head feature-branch
